"""create_world_events_table

Revision ID: 4c436ce92d8e
Revises: b6f58d8f00ab
Create Date: 2025-11-19 10:04:35.709297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4c436ce92d8e'
down_revision: Union[str, None] = 'b6f58d8f00ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_events',
    sa.Column('id', sa.String(length=36), nullable=False, comment='WorldEvent UUID'),
    sa.Column('world_id', sa.String(length=36), nullable=False, comment='World ID this event belongs to'),
    sa.Column('t', sa.Float(), nullable=False, comment='Objective timestamp in world time'),
    sa.Column('label_time', sa.String(length=255), nullable=False, comment='Human-readable time label'),
    sa.Column('location_id', sa.String(length=36), nullable=True, comment='Location reference (for future GraphRAG)'),
    sa.Column('type', sa.String(length=100), nullable=False, comment='Event type (incident, glitch, meeting, etc.)'),
    sa.Column('summary', sa.Text(), nullable=False, comment='Brief description of the event'),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False, comment='Tags for categorization'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last update'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_world_events_type', 'world_events', ['type'], unique=False)
    op.create_index(op.f('ix_world_events_world_id'), 'world_events', ['world_id'], unique=False)
    op.create_index('ix_world_events_world_t', 'world_events', ['world_id', 't'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_world_events_world_t', table_name='world_events')
    op.drop_index(op.f('ix_world_events_world_id'), table_name='world_events')
    op.drop_index('ix_world_events_type', table_name='world_events')
    op.drop_table('world_events')
    # ### end Alembic commands ###
