"""create_stories_table

Revision ID: 4ef2e50fa551
Revises: 4c436ce92d8e
Create Date: 2025-11-19 10:05:54.419069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef2e50fa551'
down_revision: Union[str, None] = '4c436ce92d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Story UUID'),
    sa.Column('world_id', sa.String(length=36), nullable=False, comment='World ID this story belongs to'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Story title'),
    sa.Column('synopsis', sa.Text(), nullable=True, comment='Brief summary'),
    sa.Column('theme', sa.String(length=255), nullable=True, comment='Central theme'),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='storystatus'), nullable=False, comment='Current status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last update'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_world_id'), 'stories', ['world_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_world_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
