"""add_password_hash_to_users

Revision ID: 6c1c6123e69f
Revises: f94378c3be57
Create Date: 2025-11-21 09:42:00.136019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1c6123e69f'
down_revision: Union[str, None] = 'f94378c3be57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add column as nullable first (to handle existing users)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Bcrypt password hash'))

    # Step 2: Set temporary password for existing users
    # Using bcrypt hash for password "TEMP_PASSWORD_PLEASE_CHANGE"
    # This is: $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY0Jz9.lqmB7eMK
    op.execute("""
        UPDATE users
        SET password_hash = '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY0Jz9.lqmB7eMK'
        WHERE password_hash IS NULL
    """)

    # Step 3: Make column NOT NULL
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               nullable=False)

    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email address (stored lowercase for case-insensitive uniqueness)',
               existing_comment='User email address',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email address',
               existing_comment='User email address (stored lowercase for case-insensitive uniqueness)',
               existing_nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
