"""create_story_beats_table

Revision ID: 9678c121e009
Revises: 4ef2e50fa551
Create Date: 2025-11-19 10:06:52.376571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9678c121e009'
down_revision: Union[str, None] = '4ef2e50fa551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_beats',
    sa.Column('id', sa.String(length=36), nullable=False, comment='StoryBeat UUID'),
    sa.Column('story_id', sa.String(length=36), nullable=False, comment='Story ID this beat belongs to'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Ordering within the story'),
    sa.Column('content', sa.Text(), nullable=False, comment='The actual text content'),
    sa.Column('type', sa.Enum('SCENE', 'SUMMARY', 'NOTE', name='beattype'), nullable=False, comment='Beat type'),
    sa.Column('world_event_id', sa.String(length=36), nullable=True, comment='Optional link to a canonical world event'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last update'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_event_id'], ['world_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_beats_story_id'), 'story_beats', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_beats_story_id'), table_name='story_beats')
    op.drop_table('story_beats')
    # ### end Alembic commands ###
