"""create_worlds_table

Revision ID: b6f58d8f00ab
Revises: 
Create Date: 2025-11-19 10:03:37.137819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f58d8f00ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID from Supabase Auth'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('settings', sa.JSON(), nullable=False, comment='User preferences (language, theme, default_model, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last update'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('worlds',
    sa.Column('id', sa.String(length=36), nullable=False, comment='World UUID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Owner user ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='World name'),
    sa.Column('description', sa.Text(), nullable=True, comment='General pitch/summary'),
    sa.Column('tone', sa.String(length=500), nullable=True, comment='Narrative tone'),
    sa.Column('backdrop', sa.Text(), nullable=True, comment='World bible, overarching lore'),
    sa.Column('laws', sa.JSON(), nullable=False, comment='World rules (physics, metaphysics, social, forbidden)'),
    sa.Column('chronology_mode', sa.Enum('LINEAR', 'FRAGMENTED', 'TIMELESS', name='chronologymode'), nullable=False, comment='How time flows in this world'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of creation'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of last update'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_user_id'), 'worlds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worlds_user_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
