<script lang="ts">
    import type { StoryBeat, BeatResponse } from "$lib/types";
    import AIThoughtsPanel from "./AIThoughtsPanel.svelte";

    export let beat: StoryBeat;
    export let storyId: string;
    export let onModify: (beat: StoryBeat) => void;
    export let onDelete: (beatId: string) => void;
    export let onUpdate: () => void;

    let isExpanded = true;

    function toggleExpanded() {
        isExpanded = !isExpanded;
    }
</script>

<div
    class="relative rounded-lg border border-gray-300 bg-white shadow-sm transition-shadow hover:shadow-md"
>
    <div class="px-6 py-5">
        <!-- Header with drag handle and controls -->
        <div class="flex items-center justify-between mb-2">
            <div class="flex items-center gap-2">
                <!-- Drag Handle -->
                <button
                    class="cursor-grab active:cursor-grabbing text-gray-400 hover:text-gray-600 p-1 rounded hover:bg-gray-100 drag-handle"
                    aria-label="Drag to reorder"
                    tabindex="-1"
                >
                    <svg class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8h16M4 16h16" />
                    </svg>
                </button>

                <!-- Beat Type Badge -->
                <span
                    class="inline-flex items-center rounded-md bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10"
                >
                    {beat.type}
                </span>

                <!-- Beat Number -->
                <span class="text-sm font-medium text-gray-900">
                    Beat #{beat.order_index}
                </span>

                <!-- Time Label -->
                {#if beat.local_time_label}
                    <span
                        class="inline-flex items-center rounded-md bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 ring-1 ring-inset ring-indigo-600/20"
                    >
                        {beat.local_time_label}
                    </span>
                {/if}

                <!-- Generated By Badge -->
                {#if beat.generated_by === "ai"}
                    <span
                        class="inline-flex items-center rounded-md bg-purple-50 px-2 py-1 text-xs font-medium text-purple-700 ring-1 ring-inset ring-purple-600/20"
                    >
                        AI Generated
                    </span>
                {:else if beat.generated_by === "collaborative"}
                    <span
                        class="inline-flex items-center rounded-md bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700 ring-1 ring-inset ring-blue-600/20"
                    >
                        Collaborative
                    </span>
                {:else}
                    <span
                        class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20"
                    >
                        Manual
                    </span>
                {/if}

                <!-- Expand/Collapse Button -->
                <button
                    on:click={toggleExpanded}
                    class="text-xs text-gray-500 hover:text-gray-700 ml-2"
                    aria-label={isExpanded ? "Collapse" : "Expand"}
                >
                    {isExpanded ? "▼" : "▶"}
                </button>
            </div>

            <!-- Action Buttons -->
            <div class="flex items-center gap-2">
                <button
                    on:click={() => onModify(beat)}
                    class="text-xs text-purple-600 hover:text-purple-500 font-medium"
                >
                    🤖 Modify with AI
                </button>
                <a
                    href="/stories/{storyId}/beats/{beat.id}/edit"
                    class="text-xs text-indigo-600 hover:text-indigo-500"
                >
                    Edit
                </a>
                <button
                    on:click={() => onDelete(beat.id)}
                    class="text-xs text-red-600 hover:text-red-500"
                >
                    Delete
                </button>
            </div>
        </div>

        <!-- Summary (always visible when collapsed) -->
        {#if beat.summary}
            <p class="text-sm font-medium text-gray-700 mb-2">
                {beat.summary}
            </p>
        {/if}

        <!-- Content (collapsible) -->
        {#if isExpanded}
            <p class="text-sm text-gray-600 whitespace-pre-wrap">
                {beat.content}
            </p>
        {/if}

        <!-- World Event Link -->
        {#if beat.world_event_id}
            <div class="mt-3 pt-3 border-t border-gray-200">
                <p class="text-xs text-gray-500">
                    Linked to World Event ID: {beat.world_event_id}
                </p>
            </div>
        {/if}
    </div>

    <!-- AI Thoughts Panel -->
    {#if isExpanded && (beat.generated_by === "ai" || beat.generation_reasoning)}
        <div class="px-6 pb-5">
            <AIThoughtsPanel
                beat={beat as BeatResponse}
                onUpdate={onUpdate}
            />
        </div>
    {/if}
</div>

<style>
    .cursor-grab:active {
        cursor: grabbing;
    }

    .drag-handle {
        touch-action: none;
    }
</style>
